version: "3.7"

services:
  database:
    image: postgres
    container_name: adopt-me
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adoptme
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
